# Home Assistant FRPC Add-On Configuration
# This file defines the necessary configuration for FRPC to connect to a remote FRP server

server: "your.frp.server"       # The FRP server address
server_port: 7000               # The port of the FRP server (default is 7000)
token: "your-frp-token"         # The token for authentication with the FRP server

ports:
  - local_port: 8080            # Local port to be forwarded (e.g., HTTP)
    remote_port: 80             # Remote port on the server
  - local_port: 5000            # Another local port to be forwarded
    remote_port: 5000           # Remote port for service B