name: Build and Publish FRPC Add-On

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7,linux/386 -t ghcr.io/sunboss/homeassistant-frpc:$(date +'%Y%m%d').1 .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        run: |
          docker push ghcr.io/sunboss/homeassistant-frpc:$(date +'%Y%m%d').1